apiVersion: v1
kind: Pod
metadata:
    name: myapp
    labels:
        component: web
spec:
    containers:
        - name: containerjk
          image: docker.io/axelsilverdew/complex_client
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
              - containerPort: 3000