services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: simple_blog_api

  api:
    build: ./
    restart: always
    image: docker.io/jkaja639/simple_blog_api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: simple_blog_api
      PORT: 3000
    ports:
      - "8081:3000"  # Map port 3000 inside the container to port 8081 on the host
