apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
spec:
    selector:
        matchLabels:
            component: api
    template:
        metadata:
            labels:
                component: api
        spec:
            containers:
                - name: api-app
                  image: docker.io/jkaja639/simple_blog_api
                  resources:
                      limits:
                          memory: "256Mi"
                          cpu: "500m"
                  ports:
                      - containerPort: 3000
                  env:
                      - name: POSTGRES_HOST
                        value: postgres
                      - name: POSTGRES_PORT
                        value: "5432"
                      - name: POSTGRES_USERNAME
                        value: postgres
                      - name: POSTGRES_DB
                        value: simple_blog_api
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: pgpassword
                                key: POSTGRES_PASSWORD
